### ISSUE TITLE
As a first time user, I want to be able to know what is expected of me on the home page so that I can easily navigate and find information

### ISSUE THREAD

**Issue by paulie-o74** [rashdogg74/newsbox86#1]
**Acceptance Criteria**

- [x] Navigation bar
- [x] Easy to identify website purpose
- [x] Text is easy to read
- [x]  It's easy to find where to sign-up
- [x]  Blog is easy to find
