### ISSUE TITLE
As a Site User, I want to be able to sort the list of available posts, so that I can identify posts based on featured, date added, oldest to newest

### ISSUE THREAD

**Issue by paulie-o74** [rashdogg74/newsbox86#13]
Acceptance Criteria

- [ ] Sorting functionality based on Featured
- [ ] Sorting functionality based on Date Added
- [x] Sorting functionality based on Oldest to Newest

**Comment by paulie-o74** [comment]
Feature will not be built in this iteration of the project... closing ticket
