### ISSUE TITLE
As a Site Owner, I want to be able to review all posts, comments, categories, users, and likes so that I can maintain the site and remove any offensive content

### ISSUE THREAD

**Issue by paulie-o74** [rashdogg74/newsbox86#17]
**Acceptance Criteria**

When a comment or post is submitted by other site users, the site owner can:

- [x] Review posts, comments, categories, users 
- [x] Accept and publish acceptable content
- [x] Reject and not publish offensive or inappropriate content
