### ISSUE TITLE
As a Site owner, I want to be able to direct users to my social profiles, so that I can increase social interaction and attract new users

### ISSUE THREAD

**Issue by paulie-o74** [rashdogg74/newsbox86#19]
Acceptance Criteria

- [x] Social profiles in footer
- [x] Social profiles hyperlinks added
- [ ] Social profiles properly styled
