### ISSUE TITLE
As a Site owner, I want all areas of the site to function correctly and have no bugs, so that I can ensure an enjoyable browsing experience for all newcomers

### ISSUE THREAD

**Issue by paulie-o74** [rashdogg74/newsbox86#20]
Acceptance Criteria

- [ ] E2E testing performed on all functionalities to ensure site is working as intended
- [ ] Docmentation of testing and outcomes
- [ ] Bugs highlighted and fixed or added to Read Me file
