### ISSUE TITLE
As a Site User I want to be able to create/read/update/delete a comment/post, so that I can alter how I would like my post to look to allow for maximum engagement

### ISSUE THREAD

**Issue by paulie-o74** [rashdogg74/newsbox86#6]
**Acceptance Criteria**

- [ ]  If logged in, user can add a comment or post
- [ ]  If logged in, user can update their own comments and posts
- [ ]  If logged in, user can delete their own comments or posts
- [ ]  If logged in, after submitting a comment or post, a message appears saying that post or comment is awaiting approval by site administrator
- [ ]  If not logged in, users cannot access any of the functionality to add, update, delete or submit any posts or comments 
- [ ]  if not logged in, users have a read-only view of the website
