### ISSUE TITLE
As a Site User I want to be able to easily create a profile,  so that I can post to the blog, engage and comment on other posts

### ISSUE THREAD

**Issue by paulie-o74** [rashdogg74/newsbox86#8]
**Acceptance Criteria**

- [x] User can create a profile from the log-in page
- [ ] User can access restricted functionality: post stories & comments, edit stories, delete stories, engage with other stories & comments, like posts
- [x] Success pop-up message upon successful profile creation (sign-up)
- [x] Success pop-up message upon sign-in (after initial sign up)
