### ISSUE TITLE
As a Site User I want to be able to easily login and log out, so that I can ensure my account is secure

### ISSUE THREAD

**Issue by paulie-o74** [rashdogg74/newsbox86#9]
**Acceptance Criteria**

- [x] Dynamic Navigation bar with login when the user is not logged in which takes you to the log-in page
- [x] Dynamic Navigation bar with Sign out when user is logged in
- [x]  Success pop-up message upon successful sign-up
- [x] Succes pop-up message upon successful sign-in
- [x]  Success pop-up message upon sign-out
- [x]  If login attempt fails due to incorrect password, an error message shows
